### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rubiin** [rubiin/nestjs-minio#321]

**Comment by ruslanguns** [comment]
Can I implement compodoc?

**Comment by rubiin** [comment]
go for it @ruslanguns

**Comment by ruslanguns** [comment]
Seems like your src/main.ts is requiring a nest-minio-client.module.ts file that doesn't exists. I see in the git history you deleted one file two days ago and wondering if can I use it to make the app working or tell me if there's another way to make this app run

**Comment by ruslanguns** [comment]
Got it, I will just ignore the main.ts 

```ts
// main.ts
/**
 *  If you're building a standalone npm package hosting a dynamic module, you
 *  should delete this file.  Its only purpose is to bootstrap the app so that
 *  you can run the quick verification test (see nest-minio-client/nest-minio-client.module.ts)
 */
```

**Comment by rubiin** [comment]
that is an unnecessary file and i have deleted it, please sync your fork

**Comment by ruslanguns** [comment]
> that is an unnecessary file and i have deleted it, please sync your fork

Ok! thanks for quick reply

**Comment by ruslanguns** [comment]
@rubiin now you are also able to publish on Github Pages if you want! 😉

**Comment by rubiin** [comment]
This looks neat , LGTM
