### ISSUE TITLE
What is MINIO_CONNECTION?

### ISSUE THREAD

**Issue by so2liu** [rubiin/nestjs-minio#361]
Hi Rubiin,

I am new to nestjs and minio. Thank you a lot for your helpful work. I have two questions about it:

1. What is MINIO_CONNECTION in example from readme?
2. Could you please add an example about downloading things? I search around by google and every example is about uploading. I think an example for downloading in nestjs would be very helpful, since you may have to deal with stream data.

Thanks a lot.

Yang Liu

**Comment by rubiin** [comment]
Sure I can give you an example , will that be helpful?

**Comment by so2liu** [comment]
Yes, that would be very helpful.

Actually after about 8 hours searching, I have implicated download and video online playing. But since I am new to nestjs and even newer to minio, I don't know whether my code is following the best practice (if it exists). Beside, there is really no download example in the internet, which makes it especially helpful. 

Thank you a lot.

**Comment by rubiin** [comment]
are you using minio in docker or standalone. To download you just have to set the bucket policy to read and write and i you have the url, it automatically downloads

**Comment by SirMishaa** [comment]
Hello

I'm reading the documentation but finally, what's MINIO_CONNECTION ? How are we supposed to get the client from nestjs-menio? 

Actually, I've this : 
```ts
import { Injectable, Logger } from '@nestjs/common';
import { NestMinioService } from 'nestjs-minio';
import { AppLogger } from '@/core/logger/AppLogger';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class FileService {
  constructor(
    private readonly minioService: NestMinioService,
    private readonly logger: AppLogger,
    private readonly configService: ConfigService,
  ) {
    Logger.warn(this.minioService.getMinio()); // Return a kind of object, but not the client
  }

  public get client() {
    return null;
    // Todo : Return the client
  }
}
```

But I don't know how to get the client :/

**Comment by rubiin** [comment]
MINIO_CONNECTION is a token for injecting client . More on https://docs.nestjs.com/fundamentals/async-providers#injection

**Comment by rubiin** [comment]
> Hello
> 
> I'm reading the documentation but finally, what's MINIO_CONNECTION ? How are we supposed to get the client from nestjs-menio?
> 
> Actually, I've this :
> 
> ```ts
> import { Injectable, Logger } from '@nestjs/common';
> import { NestMinioService } from 'nestjs-minio';
> import { AppLogger } from '@/core/logger/AppLogger';
> import { ConfigService } from '@nestjs/config';
> 
> @Injectable()
> export class FileService {
>   constructor(
>     private readonly minioService: NestMinioService,
>     private readonly logger: AppLogger,
>     private readonly configService: ConfigService,
>   ) {
>     Logger.warn(this.minioService.getMinio()); // Return a kind of object, but not the client
>   }
> 
>   public get client() {
>     return null;
>     // Todo : Return the client
>   }
> }
> ```
> 
> But I don't know how to get the client :/

to get the client you will have to use `@Inject(MINIO_CONNECTION) private readonly minioClient` . Injecting service wont work

**Comment by SirMishaa** [comment]
Thank you very much. 

It works well, I thought MINIO_CONNECTION was a constant that we had to define ourselves. 

However, what is the type (Typescript) of ``@Inject(MINIO_CONNECTION) private readonly minioClient`` ? I have trouble finding it in the type definition file.

Thanks again. 
Regards

**Comment by SirMishaa** [comment]
I found it, finally.

Type is "Client" from minio. You should think about adding it to the definition of types.


![image](https://user-images.githubusercontent.com/42717232/108783412-bdbb8400-756d-11eb-93a1-826e72ea7ba6.png)

**Comment by rubiin** [comment]
> I found it, finally.
> 
> Type is "Client" from minio. You should think about adding it to the definition of types.
> 
> ![image](https://user-images.githubusercontent.com/42717232/108783412-bdbb8400-756d-11eb-93a1-826e72ea7ba6.png)

will be adding this asap

**Comment by rubiin** [comment]
The latest relaese should fix it. Doc is also updated, thanks for help guys
