### ISSUE TITLE
New versions are not on GitHub

### ISSUE THREAD

**Issue by hkdobrev** [rubiin/nestjs-minio#509]
### Describe the bug

There are new versions of the package on npm.
However, these versions are not on the GitHub repository at all.
It's hard to see what was changed in those versions and could be interpreted as an npm package hijack.

<img width="1273" alt="Screenshot 2023-03-20 at 11 12 27" src="https://user-images.githubusercontent.com/506129/226295638-80290b49-83bf-44cd-aeba-322fb569ff2f.png">
<img width="1266" alt="Screenshot 2023-03-20 at 11 12 46" src="https://user-images.githubusercontent.com/506129/226295643-6f065723-f0cb-4dcb-86b6-df4aa1d15bc2.png">
<img width="1370" alt="Screenshot 2023-03-20 at 11 12 57" src="https://user-images.githubusercontent.com/506129/226295649-2520eae5-95bb-4bd7-bb58-1fe6548a5b92.png">

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/rubiin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/rubiin/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kungfu321** [comment]
any update on this

**Comment by rubiin** [comment]
let me look at tonight

**Comment by rubiin** [comment]
Fixed https://github.com/rubiin/nestjs-minio/commit/ef8b12dfdf483aeb7afe3de1494e20e114739e23

**Comment by hkdobrev** [comment]
Thank you, @rubiin!
