### ISSUE TITLE
Printing the credentials to console

### ISSUE THREAD

**Issue by LambdaXCF** [rubiin/nestjs-minio#64]
I think it might be a good idea to remove [this log statement](https://github.com/rubiin/nestjs-minio/blob/b193275621709d0172b09042880504af50b1d936/src/nest-minio.service.ts#L19) from the `NestMinioService` because it also prints the `accessKey` and `secretKey` to the console.

**Comment by rubiin** [comment]
Sure thing. Pr are welcomed

**Comment by Sascha-T** [comment]
Is this an acceptable solution?
